name = "legos"
version = "1.0.2"

description = "Layout and style that's easy to refactor, all without thinking about CSS."
licences = ["BSD-3-Clause"]
repository = { type = "github", user = "NduatiK", repo = "legos" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.3.4 and < 6.0.0"
gleam_community_maths = ">= 2.0.0 and < 3.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
